import React from "react";
import {
  Body,
  Column,
  Container,
  Font,
  Head,
  Html,
  Img,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from "@react-email/components";
import {
  BrandFooter,
  CardLabel,
  CtaButton,
  HeaderBanner,
  Masthead,
  SponsorsCard,
  SITE,
  bebas,
  cardBase,
  colors as c,
  mono,
  system,
} from "./components/brand";

interface NationalsRaceReportEmailProps {
  email?: string;
}

const NBSP = " ";
const DOT = `${NBSP}${NBSP}·${NBSP}${NBSP}`;

// Patrick's own opening line, used verbatim as the subject. Do not rewrite it.
export const nationalsRaceReportSubject =
  "I wanted it so badly, I forgot how to race";

const PREVIEW =
  "Fourth place at Paratriathlon Nationals, and the lesson that was harder to swallow than the result.";

const DONATE_URL = "https://give.dare2tri.org/fundraiser/6928347";
// Matches the SuperTri Chicago entry in lib/race-data.ts.
const CHICAGO_URL = "https://by.supertri.com/chicago-triathlon/";

/**
 * Race-report photos live under /public/email/nationals-recap/, generated by
 * scripts/optimize-nationals-recap-assets.mjs from the originals in
 * assets/source/nationals-recap/.
 */
const img = {
  preRace: `${SITE}/email/nationals-recap/nr-pre-race.jpg`,
  swim: `${SITE}/email/nationals-recap/nr-swim.jpg`,
  waterExit: `${SITE}/email/nationals-recap/nr-water-exit.jpg`,
  bike: `${SITE}/email/nationals-recap/nr-bike.jpg`,
};

export default function NationalsRaceReportEmail({
  email,
}: NationalsRaceReportEmailProps) {
  return (
    <Html lang="en" dir="ltr">
      <Head>
        <meta name="color-scheme" content="light" />
        <meta name="supported-color-schemes" content="light" />
        <Font
          fontFamily="Bebas Neue"
          fallbackFontFamily={["Arial", "Helvetica", "sans-serif"]}
          webFont={{
            url: `${SITE}/fonts/BebasNeue-Regular.woff2`,
            format: "woff2",
          }}
          fontWeight={400}
          fontStyle="normal"
        />
        <style>{":root { color-scheme: light; }"}</style>
      </Head>

      <Preview>{PREVIEW}</Preview>

      <Body style={styles.bodyEl}>
        <Container style={styles.wrapper}>
          <Section style={styles.topAccent} />

          <Masthead tag="RACE REPORT" sub="AUGUST 9, 2026" />
          <HeaderBanner />

          {/* Poster — Patrick's opening line over the pre-race dock portrait */}
          <Section style={styles.posterCard}>
            <Section style={styles.posterTop}>
              <Text style={styles.ecgLine}>{"---------/\\__/\\---------"}</Text>
              <Text style={styles.headlineKicker}>NATIONALS.</Text>
              <Text style={styles.headlineAccent}>
                I WANTED IT SO BADLY, I FORGOT HOW TO RACE
              </Text>
            </Section>
            <Img
              src={img.preRace}
              width="560"
              alt="Patrick Wingert in his wetsuit on the dock before the start at Paratriathlon Nationals"
              style={styles.posterPhoto}
            />
            <Section style={styles.posterBand}>
              <Text style={styles.bandTitle}>
                USA TRIATHLON PARATRIATHLON NATIONAL CHAMPIONSHIPS
              </Text>
              <Text style={styles.bandSub}>
                MILWAUKEE, WI{DOT}AUGUST 9, 2026
              </Text>
            </Section>
          </Section>

          {/* The result. Deliberately sombre: a bright card would fight the copy. */}
          <Section style={styles.resultCard}>
            <Text style={styles.resultLabel}>FINAL PLACING</Text>
            <Text style={styles.resultNumber}>4TH</Text>
            <Text style={styles.resultNote}>
              FIRST TIME OFF THE PODIUM THIS SEASON
            </Text>
          </Section>

          {/* Opening letter */}
          <Section style={styles.card}>
            <CardLabel>A NOTE FROM PATRICK</CardLabel>
            <Text style={styles.bodyText}>
              It has taken me a few days to admit that to myself and write this
              email.
            </Text>
            <Text style={styles.bodyText}>
              USAT Paratriathlon Nationals was the race I had been building
              toward all year. The goal was the podium. I had worked for it,
              sacrificed for it, and thought about it for months.
            </Text>
            <Text style={styles.bodyText}>
              I finished fourth. For the first time this season, I missed the
              podium.
            </Text>
            <Text style={styles.pullLineLast}>
              And honestly, it fucking hurt.
            </Text>
          </Section>

          {/* The honest accounting */}
          <Section style={styles.card}>
            <CardLabel>WHAT I COULD HAVE DONE DIFFERENTLY</CardLabel>
            <Text style={styles.bodyText}>
              Not because fourth place is a bad result. It isn&rsquo;t. But
              because I knew I was capable of more, and because when I looked
              honestly at the race, I knew there were things I could have done
              differently.
            </Text>
            <Text style={styles.bodyText}>
              I didn&rsquo;t train enough in the water. I knew swimming was my
              weakness. I knew it needed more attention, but I thought I could
              will myself through it and make up the difference on the bike and
              run.
            </Text>
            <Text style={styles.pullLine}>I couldn&rsquo;t.</Text>
            <Text style={styles.bodyTextLast}>
              The swim was terrible, and my race was in trouble long before I
              ever got out of the water. Then I struggled with my prosthetic
              during pre-transition at the water exit. I fell running with my
              bike out of T1. Instead of settling down and getting back into my
              race, I got angry. I rode the bike too hard trying to make up
              time, burned the match I needed for the run, and eventually blew
              up.
            </Text>
          </Section>

          {/* The mental mistake */}
          <Section style={styles.card}>
            <CardLabel>THE BIGGEST MISTAKE</CardLabel>
            <Text style={styles.bodyText}>
              But the physical mistakes weren&rsquo;t the biggest lesson I took
              away from Milwaukee.
            </Text>
            <Text style={styles.pullLine}>
              The biggest mistake happened in my head.
            </Text>
            <Text style={styles.bodyText}>
              Not because I didn&rsquo;t work hard enough. Not because I
              didn&rsquo;t want it badly enough. Almost the opposite.
            </Text>
            <Text style={styles.bodyText}>
              I wanted it so badly that I let the pressure of the goal speak
              louder than the work I had already done.
            </Text>
            <Text style={styles.bodyText}>
              I let the other guys unknowingly get in my head. I spent too much
              of the weekend thinking about who else was racing, how fast they
              were, what they had done, and what I needed to do to beat them.
            </Text>
            <Text style={styles.bodyTextLast}>
              I let one bad swim become a bad race. I let anger dictate how I
              rode the bike. I stopped experiencing the race and started trying
              to negotiate with it.
            </Text>
            <Section style={styles.manifestoBlock}>
              <Text style={styles.manifestoLine}>I forgot how to race.</Text>
            </Section>
          </Section>

          {/* The swim. Full frame on purpose: the empty water is the point. */}
          <Section style={styles.photoCard}>
            <Img
              src={img.swim}
              width="560"
              alt="Patrick Wingert alone in the open water during the swim leg at Paratriathlon Nationals"
              style={styles.photo}
            />
            <Section style={styles.captionBar}>
              <Text style={styles.captionText}>
                THE SWIM{DOT}AUGUST 9, 2026
              </Text>
            </Section>
          </Section>

          {/* Sunday */}
          <Section style={styles.card}>
            <CardLabel>SUNDAY</CardLabel>
            <Text style={styles.bodyText}>
              And that&rsquo;s a much harder lesson to swallow than finishing
              fourth.
            </Text>
            <Text style={styles.bodyText}>
              That realization didn&rsquo;t happen on Sunday.
            </Text>
            <Text style={styles.pullLine}>Sunday was hard.</Text>
            <Text style={styles.bodyText}>
              I was disappointed. Angry. Bitter. I felt like I had failed. I
              felt like I had let myself down, and let down my friends, my
              family, my sponsors, and everyone who had invested in this journey
              with me.
            </Text>
            <Text style={styles.bodyText}>Then I watched the awards ceremony.</Text>
            <Text style={styles.bodyText}>
              Three other athletes got to experience the moment they had worked
              their asses off for while I watched from the side stage.
            </Text>
            <Text style={styles.bodyText}>
              I was genuinely happy for them. I am. But watching someone else
              live the moment you wanted for yourself is a pretty uncomfortable
              experience.
            </Text>
            <Text style={styles.bodyText}>
              Back at the hotel, I told Melissa, &ldquo;This feeling fucking
              sucks, and I&rsquo;m going to make sure I never have to feel this
              again.&rdquo; I also told her I was going to use it.
            </Text>
            <Text style={styles.bodyText}>But I needed a few days.</Text>
            <Text style={styles.bodyTextLast}>
              I needed to sit with the emotions instead of immediately trying to
              turn them into motivation. I went through all five stages of
              grief, and some of them more than once. I had to reflect honestly:
              the good, the bad, the mistakes, the progress, and everything in
              between.
            </Text>
          </Section>

          {/* Wednesday */}
          <Section style={styles.card}>
            <CardLabel>WEDNESDAY</CardLabel>
            <Text style={styles.bodyTextLast}>
              Then on Wednesday, my sister Kayla said something that completely
              reframed the whole experience for me.
            </Text>
          </Section>

          {/* Kayla's quote — set in the body face, not display caps. This is the
              turning point of the email and it should read like a person
              talking, not like a slogan. */}
          <Section style={styles.quoteCard}>
            <Text style={styles.quoteMark}>&ldquo;</Text>
            <Text style={styles.quoteTextSoft}>
              Sometimes &lsquo;be harder&rsquo; might mean be kinder to
              yourself. I can&rsquo;t think of anything harder than that,
              honestly.
            </Text>
            <Text style={styles.quoteAttr}>KAYLA{DOT}PATRICK&rsquo;S SISTER</Text>
          </Section>

          <Section style={styles.card}>
            <Section style={styles.manifestoBlockTight}>
              <Text style={styles.manifestoLine}>Fuck.</Text>
            </Section>
            <Text style={styles.bodyText}>She was right.</Text>
            <Text style={styles.bodyText}>
              In my professional life, I encourage failure. I tell people that
              failure is where we learn, where we grow, and where we figure out
              what needs to change. I believe that deeply. But when it was my
              failure, I struggled to take my own advice.
            </Text>
            <Text style={styles.bodyText}>Maybe that&rsquo;s part of the lesson.</Text>
            <Text style={styles.pullLineLast}>
              The question isn&rsquo;t whether I was good enough. It&rsquo;s
              whether I&rsquo;m brave enough to keep going and find out how good
              I can be.
            </Text>
          </Section>

          {/* Seven */}
          <Section style={styles.card}>
            <CardLabel>SEVEN</CardLabel>
            <Text style={styles.bodyText}>
              Because this is only my seventh race.
            </Text>
            <Text style={styles.bodyText}>
              Seven. That&rsquo;s a lot, and it&rsquo;s also not many. The guys
              who beat me have years in this sport, training, racing, learning,
              failing, and figuring things out.
            </Text>
            <Text style={styles.bodyText}>I have one year.</Text>
            <Text style={styles.bodyTextLast}>Most people never even start.</Text>
            <Section style={styles.manifestoBlock}>
              <Text style={styles.manifestoLineAccent}>But I started.</Text>
            </Section>
          </Section>

          {/* The two numbers that argue back at the self-criticism */}
          <Section style={styles.statBand}>
            <Row>
              <Column style={styles.statColLeft}>
                <Text style={styles.statNumber}>7</Text>
                <Text style={styles.statLabel}>RACES</Text>
              </Column>
              <Column style={styles.statColRight}>
                <Text style={styles.statNumber}>1</Text>
                <Text style={styles.statLabel}>YEAR IN THE SPORT</Text>
              </Column>
            </Row>
          </Section>

          {/* The weekend around him */}
          <Section style={styles.card}>
            <CardLabel>THE WEEKEND AROUND ME</CardLabel>
            <Text style={styles.bodyText}>
              I&rsquo;m also not going to let my disappointment take away from
              what was an incredible weekend for the athletes and community
              around me.
            </Text>
            <Text style={styles.bodyText}>
              I&rsquo;m proud of my teammates and of every athlete who showed up
              and put themselves on the line in Milwaukee. Congratulations to
              everyone who raced, podium or not. It takes something to put
              yourself out there and find out what happens.
            </Text>
            <Text style={styles.bodyTextLast}>
              And congratulations to the entire Dare2Tri community.
            </Text>
          </Section>

          {/* Dare2Tri's weekend */}
          <Section style={styles.d2tCard}>
            <Text style={styles.d2tLabel}>DARE2TRI AT NATIONALS</Text>
            <Row>
              <Column style={styles.d2tColLeft}>
                <Text style={styles.d2tNumber}>32</Text>
                <Text style={styles.d2tUnit}>PODIUMS</Text>
              </Column>
              <Column style={styles.d2tColRight}>
                <Text style={styles.d2tNumber}>4</Text>
                <Text style={styles.d2tUnit}>NATIONAL TITLES</Text>
              </Column>
            </Row>
          </Section>

          <Section style={styles.card}>
            <Text style={styles.pullLine}>That&rsquo;s fucking incredible.</Text>
            <Text style={styles.bodyTextLast}>
              Being part of this community is one of the things I&rsquo;m most
              grateful for. I get to train, race, learn, and grow alongside
              people who remind me that this sport is about so much more than
              results.
            </Text>
          </Section>

          {/* The water exit. Placed here, the same failure reads as support. */}
          <Section style={styles.photoCard}>
            <Img
              src={img.waterExit}
              width="560"
              alt="Patrick Wingert helped out of the water at pre-transition by two volunteers"
              style={styles.photo}
            />
            <Section style={styles.captionBar}>
              <Text style={styles.captionText}>NOBODY GETS OUT ALONE</Text>
            </Section>
          </Section>

          {/* Holding both things */}
          <Section style={styles.card}>
            <CardLabel>BOTH THINGS AT ONCE</CardLabel>
            <Text style={styles.bodyText}>
              So I&rsquo;m trying to hold both things at the same time.
            </Text>
            <Text style={styles.bodyText}>
              I can be disappointed in my race and proud of the work that got me
              there.
            </Text>
            <Text style={styles.bodyText}>
              And I can be harder on myself without being cruel to myself.
            </Text>
            <Text style={styles.bodyText}>
              That&rsquo;s the balance I&rsquo;m still learning.
            </Text>
            <Text style={styles.bodyText}>
              So I&rsquo;m going to keep showing up. I&rsquo;m going to train
              the weaknesses instead of trying to will my way through them.
              I&rsquo;m going to keep learning how to race instead of only
              learning how to train. And I&rsquo;m going to get better at being
              present enough to enjoy the process.
            </Text>
            <Text style={styles.pullLine}>
              Because the process is the journey.
            </Text>
            <Text style={styles.bodyText}>
              And I&rsquo;m not ready for the journey to end.
            </Text>
            <Text style={styles.bodyTextLast}>
              Which brings me to what&rsquo;s next.
            </Text>
          </Section>

          {/* ONE MORE poster — bookends the opening poster, inverted */}
          <Section style={styles.posterCard}>
            <Section style={styles.posterTopDark}>
              <Text style={styles.oneMoreKicker}>WHAT&rsquo;S NEXT</Text>
              <Text style={styles.oneMore}>ONE MORE</Text>
            </Section>
            <Img
              src={img.bike}
              width="560"
              alt="Patrick Wingert down in the aero bars on the bike course"
              style={styles.posterPhoto}
            />
            <Section style={styles.posterBand}>
              {/* Inline anchor, not a wrapper around the <p>s: Outlook's Word
                  renderer mangles block elements nested inside an <a>. */}
              <Text style={styles.bandTitle}>
                <Link href={CHICAGO_URL} style={styles.bandLink}>
                  SUPERTRI CHICAGO
                </Link>
              </Text>
              <Text style={styles.bandSub}>
                CHICAGO, IL{DOT}AUGUST 23, 2026
              </Text>
            </Section>
          </Section>

          {/* Chicago */}
          <Section style={styles.card}>
            <Text style={styles.bodyText}>
              My hometown. My home race. One more sprint to close out the
              season.
            </Text>
            <Text style={styles.bodyText}>
              This one is going to be different. I&rsquo;m not interested in
              spending race week worrying about who is next to me or what
              someone else is doing. I&rsquo;m going to race my race, take in
              the experience, and enjoy the fact that I get to do this at all.
            </Text>
            <Text style={styles.pullLine}>
              And if you&rsquo;re in Chicago, come out and make some noise.
            </Text>
            <Section style={styles.manifestoBlock}>
              <Text style={styles.comeLine}>Come cheer.</Text>
              <Text style={styles.comeLine}>Come heckle.</Text>
              <Text style={styles.comeLine}>
                Come find me on the course and give me a high five.
              </Text>
              <Text style={styles.comeLine}>
                Come remind me to enjoy the damn thing.
              </Text>
              <Text style={styles.comeLine}>Come have an NA beer afterwards.</Text>
            </Section>
            <Text style={styles.bodyTextLast}>
              I&rsquo;ve got one more sprint triathlon this season. And I still
              have a lot to learn.
            </Text>
          </Section>

          {/* Thanks */}
          <Section style={styles.card}>
            <CardLabel>THANK YOU</CardLabel>
            <Text style={styles.bodyText}>
              To my family, friends, teammates, mentors, sponsors, and everyone
              who has supported me this year, thank you. Thank you for believing
              in me, especially when I didn&rsquo;t have the perspective to
              believe in myself.
            </Text>
            <Text style={styles.bodyTextLast}>
              And to the sponsors and partners who make this possible, your
              support means more than a logo on a race kit. It allows me to
              chase something that, a year ago, I wasn&rsquo;t sure was
              possible.
            </Text>
          </Section>

          <SponsorsCard />

          {/* Dare2Tri fundraiser */}
          <Section style={styles.missionCard}>
            <Text style={styles.missionText}>
              If you want to help create that same opportunity for the next
              adaptive athlete, support Dare2Tri through the link below.
            </Text>
            <CtaButton href={DONATE_URL}>
              SUPPORT MY FUNDRAISER{NBSP}{NBSP}&rarr;
            </CtaButton>
            <Section style={styles.missionDivider} />
            <Text style={styles.donationText}>
              Dare2Tri is a 501(c)(3) charitable organization. Every gift is
              tax-deductible and creates access for adaptive athletes.
            </Text>
          </Section>

          {/* Close */}
          <Section style={styles.card}>
            <Section style={styles.manifestoBlockTop}>
              <Text style={styles.manifestoLineSm}>
                Comparison changes nothing.
              </Text>
              <Text style={styles.manifestoLineSmAccent}>
                Consistency changes everything.
              </Text>
            </Section>
            <Section style={styles.signatureBlock}>
              <Text style={styles.signature}>Patrick Wingert</Text>
              <Text style={styles.signatureRole}>
                ADAPTIVE ATHLETE{DOT}DARE2TRI ELITE TEAM 2026
              </Text>
            </Section>
            <Section style={styles.psBlock}>
              <Text style={styles.psText}>
                <span style={styles.psLead}>P.S.</span> August 23. SuperTri
                Chicago.{" "}
                <Link href={CHICAGO_URL} style={styles.inlineLink}>
                  Find me at the finish line.
                </Link>
              </Text>
            </Section>
          </Section>

          <BrandFooter email={email} />
        </Container>
      </Body>
    </Html>
  );
}

const styles: Record<string, React.CSSProperties> = {
  bodyEl: {
    backgroundColor: c.canvas,
    fontFamily: system,
    margin: 0,
    padding: "28px 0",
  },
  wrapper: {
    backgroundColor: c.canvas,
    maxWidth: "620px",
    margin: "0 auto",
  },
  topAccent: {
    backgroundColor: c.orange,
    height: "5px",
    width: "100%",
    borderRadius: "3px",
  },

  /* Poster */
  posterCard: {
    ...cardBase,
    padding: 0,
    overflow: "hidden",
  },
  posterTop: {
    padding: "34px 34px 28px",
    textAlign: "center" as const,
  },
  ecgLine: {
    fontFamily: mono,
    fontSize: "13px",
    color: c.orange,
    margin: "0 0 20px",
    lineHeight: "1",
    textAlign: "center" as const,
  },
  headlineKicker: {
    fontFamily: bebas,
    fontSize: "28px",
    lineHeight: "1",
    color: c.ink,
    margin: "0 0 4px",
    letterSpacing: "3px",
    textAlign: "center" as const,
  },
  headlineAccent: {
    fontFamily: bebas,
    fontSize: "42px",
    lineHeight: "0.96",
    color: c.orange,
    margin: "6px 0 0",
    letterSpacing: "1.5px",
    textAlign: "center" as const,
  },
  posterPhoto: {
    display: "block",
    width: "100%",
    maxWidth: "100%",
    height: "auto",
    border: "none",
  },
  posterBand: {
    backgroundColor: c.orange,
    padding: "18px 34px 20px",
    textAlign: "center" as const,
  },
  bandLink: {
    color: "#ffffff",
    textDecoration: "none",
  },
  bandTitle: {
    fontFamily: bebas,
    fontSize: "22px",
    lineHeight: "1.1",
    letterSpacing: "2px",
    color: "#ffffff",
    margin: "0 0 6px",
    textAlign: "center" as const,
  },
  bandSub: {
    fontFamily: mono,
    fontSize: "10px",
    letterSpacing: "2px",
    color: c.orangePale,
    margin: 0,
    textAlign: "center" as const,
  },

  /* ONE MORE poster head — dark, so it reads as a second act rather than a
     repeat of the opening poster. */
  posterTopDark: {
    backgroundColor: c.ink,
    padding: "34px 34px 30px",
    textAlign: "center" as const,
  },
  oneMoreKicker: {
    fontFamily: mono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "4px",
    color: c.orange,
    margin: "0 0 14px",
    textAlign: "center" as const,
  },
  oneMore: {
    fontFamily: bebas,
    fontSize: "64px",
    lineHeight: "0.92",
    letterSpacing: "4px",
    color: "#ffffff",
    margin: 0,
    textAlign: "center" as const,
  },

  /* Result — ink, not orange. A celebration card would fight the copy. */
  resultCard: {
    ...cardBase,
    backgroundColor: c.ink,
    border: "none",
    padding: "32px 34px 34px",
    textAlign: "center" as const,
  },
  resultLabel: {
    fontFamily: mono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "4px",
    color: c.orange,
    margin: "0 0 12px",
    textAlign: "center" as const,
  },
  resultNumber: {
    fontFamily: bebas,
    fontSize: "72px",
    lineHeight: "1",
    letterSpacing: "3px",
    color: "#ffffff",
    margin: "0 0 12px",
    textAlign: "center" as const,
  },
  resultNote: {
    fontFamily: mono,
    fontSize: "10px",
    letterSpacing: "2px",
    color: c.inkFaintText,
    margin: 0,
    textAlign: "center" as const,
  },

  /* Cards & text */
  card: cardBase,
  bodyText: {
    fontFamily: system,
    fontSize: "16px",
    lineHeight: "1.75",
    color: c.body,
    margin: "0 0 18px",
  },
  bodyTextLast: {
    fontFamily: system,
    fontSize: "16px",
    lineHeight: "1.75",
    color: c.body,
    margin: 0,
  },
  pullLine: {
    fontFamily: bebas,
    fontSize: "26px",
    lineHeight: "1.1",
    letterSpacing: "1.5px",
    color: c.ink,
    borderLeft: `3px solid ${c.orange}`,
    paddingLeft: "16px",
    margin: "26px 0",
  },
  pullLineLast: {
    fontFamily: bebas,
    fontSize: "26px",
    lineHeight: "1.1",
    letterSpacing: "1.5px",
    color: c.ink,
    borderLeft: `3px solid ${c.orange}`,
    paddingLeft: "16px",
    margin: "26px 0 0",
  },

  /* Manifesto stacks — Patrick's staccato lines set as display type */
  manifestoBlock: {
    margin: "26px 0 0",
  },
  manifestoBlockTop: {
    margin: "0 0 4px",
  },
  manifestoBlockTight: {
    margin: "0 0 14px",
  },
  manifestoLine: {
    fontFamily: bebas,
    fontSize: "34px",
    lineHeight: "1.15",
    letterSpacing: "2px",
    color: c.ink,
    margin: 0,
  },
  manifestoLineAccent: {
    fontFamily: bebas,
    fontSize: "34px",
    lineHeight: "1.15",
    letterSpacing: "2px",
    color: c.orange,
    margin: 0,
  },
  manifestoLineSm: {
    fontFamily: bebas,
    fontSize: "26px",
    lineHeight: "1.2",
    letterSpacing: "2px",
    color: c.ink,
    margin: 0,
  },
  manifestoLineSmAccent: {
    fontFamily: bebas,
    fontSize: "26px",
    lineHeight: "1.2",
    letterSpacing: "2px",
    color: c.orange,
    margin: 0,
  },
  // The Chicago invitations run long; 22px keeps each on one line in Bebas.
  comeLine: {
    fontFamily: bebas,
    fontSize: "22px",
    lineHeight: "1.3",
    letterSpacing: "1.5px",
    color: c.ink,
    margin: 0,
  },

  /* Kayla's quote card */
  quoteCard: {
    ...cardBase,
    backgroundColor: c.ink,
    border: "none",
    padding: "40px 38px 36px",
    textAlign: "center" as const,
  },
  quoteMark: {
    fontFamily: bebas,
    fontSize: "40px",
    lineHeight: "0.5",
    color: c.orange,
    margin: "0 0 14px",
    textAlign: "center" as const,
  },
  quoteTextSoft: {
    fontFamily: system,
    fontSize: "21px",
    lineHeight: "1.55",
    color: "#ffffff",
    margin: "0 0 20px",
    textAlign: "center" as const,
  },
  quoteAttr: {
    fontFamily: mono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "3px",
    color: c.orange,
    margin: 0,
    textAlign: "center" as const,
  },

  inlineLink: {
    color: c.orangeDeep,
    textDecoration: "none",
    fontWeight: 600,
  },

  /* Photo cards. Same 560px full-bleed box as posterCard, so every Img in this
     template declares width="560" — Outlook's Word engine honours the width
     attribute over the width:100% style and would otherwise leave a white gutter
     beside a full-bleed photo. */
  photoCard: {
    ...cardBase,
    padding: 0,
    overflow: "hidden",
  },
  photo: {
    display: "block",
    width: "100%",
    maxWidth: "100%",
    height: "auto",
    border: "none",
  },
  captionBar: {
    backgroundColor: "#faf9f6",
    borderTop: `1px solid ${c.borderSoft}`,
    padding: "12px 24px",
    textAlign: "center" as const,
  },
  captionText: {
    fontFamily: mono,
    fontSize: "10px",
    letterSpacing: "2px",
    color: c.muted,
    margin: 0,
  },

  /* 7 races / 1 year */
  statBand: {
    ...cardBase,
    backgroundColor: c.orange,
    border: "none",
    padding: "28px 30px",
  },
  statColLeft: {
    width: "50%",
    textAlign: "center" as const,
    verticalAlign: "top" as const,
    borderRight: `1px solid ${c.orangeDeep}`,
  },
  statColRight: {
    width: "50%",
    textAlign: "center" as const,
    verticalAlign: "top" as const,
  },
  statNumber: {
    fontFamily: bebas,
    fontSize: "56px",
    lineHeight: "1",
    letterSpacing: "2px",
    color: "#ffffff",
    margin: "0 0 6px",
    textAlign: "center" as const,
  },
  statLabel: {
    fontFamily: mono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "2px",
    color: c.orangeBurnt,
    margin: 0,
    textAlign: "center" as const,
  },

  /* Dare2Tri's weekend */
  d2tCard: {
    ...cardBase,
    backgroundColor: c.ink,
    border: "none",
    padding: "30px 30px 32px",
  },
  d2tLabel: {
    fontFamily: mono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "3px",
    color: c.orange,
    margin: "0 0 22px",
    textAlign: "center" as const,
  },
  d2tColLeft: {
    width: "50%",
    textAlign: "center" as const,
    verticalAlign: "top" as const,
    borderRight: "1px solid #2e2a22",
  },
  d2tColRight: {
    width: "50%",
    textAlign: "center" as const,
    verticalAlign: "top" as const,
  },
  d2tNumber: {
    fontFamily: bebas,
    fontSize: "56px",
    lineHeight: "1",
    letterSpacing: "2px",
    color: "#ffffff",
    margin: "0 0 6px",
    textAlign: "center" as const,
  },
  d2tUnit: {
    fontFamily: mono,
    fontSize: "10px",
    fontWeight: 700,
    letterSpacing: "2px",
    color: c.inkMutedText,
    margin: 0,
    textAlign: "center" as const,
  },

  /* Dark close */
  missionCard: {
    ...cardBase,
    backgroundColor: c.ink,
    border: "none",
    padding: "36px 38px 36px",
    textAlign: "center" as const,
  },
  missionText: {
    fontFamily: system,
    fontSize: "14px",
    lineHeight: "1.75",
    color: c.inkMutedText,
    margin: "0 0 22px",
  },
  missionDivider: {
    height: "1px",
    backgroundColor: "#2e2a22",
    margin: "28px auto 22px",
    width: "60%",
  },
  donationText: {
    fontFamily: system,
    fontSize: "13px",
    lineHeight: "1.65",
    color: c.inkMutedText,
    margin: 0,
  },

  /* Signature */
  signatureBlock: {
    borderTop: `1px solid ${c.borderSoft}`,
    marginTop: "24px",
    paddingTop: "20px",
  },
  signature: {
    fontFamily: bebas,
    fontSize: "24px",
    letterSpacing: "1.5px",
    lineHeight: "1",
    color: c.ink,
    margin: "0 0 6px",
  },
  signatureRole: {
    fontFamily: mono,
    fontSize: "9px",
    letterSpacing: "2px",
    color: c.muted,
    margin: 0,
  },

  /* P.S. */
  psBlock: {
    borderTop: `1px solid ${c.borderSoft}`,
    marginTop: "20px",
    paddingTop: "18px",
  },
  psText: {
    fontFamily: system,
    fontSize: "14px",
    lineHeight: "1.7",
    color: c.body,
    margin: 0,
  },
  psLead: {
    fontFamily: mono,
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "1.5px",
    color: c.orangeDeep,
  },
};
